export const todoTypes = {
    GET_TODOS_START: 'GET_TODOS_START',
    GET_TODOS_SUCCESS: 'GET_TODOS_SUCCESS',
    GET_TODOS_FAILURE: 'GET_TODOS_FAILURE',
    EDIT_TODO_START: 'EDIT_TODO_START',
    DELETE_TODO_START: 'DELETE_TODO_START',
    SET_TODO_SUCCESS: 'SET_TODO_SUCCESS',
}